### ISSUE TITLE
Key is blocked before config is saved

### ISSUE THREAD

**Issue by rosmayev** [igor-panteleev/WinHook#1]
**Steps to reproduce**
1. Open Key Block tab.
2. Add any key to key block.
3. Press this key.

**Expected result:**
Key input is entered.
**Actual result**
Key is not active. (Key should be inactive only after save button is pressed).

Please, note, this issue is also reproducible for remove option.

**Comment by igor-panteleev** [comment]
As designed. "**Save**" button just allow to save configuration to file.
It's not an "**apply**" button.
